"""add

Revision ID: 113caf282114
Revises: 
Create Date: 2022-04-17 16:54:03.009597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '113caf282114'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('records_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['records_id'], ['records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('records_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['records_id'], ['records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('records_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['records_id'], ['records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('records_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['records_id'], ['records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('notes_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['notes_id'], ['notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('phones')
    op.drop_table('notes')
    op.drop_table('emails')
    op.drop_table('addresses')
    op.drop_table('records')
    # ### end Alembic commands ###
